version: '3.8'
services:
  firebase-emulator:
    build:
      dockerfile: fb-dockerfile
    ports:
      - 4000:4000
      - 5000:5000
      - 5001:5001
      - 8080:8080
      - 9000:9000
      - 9099:9099
    volumes:
      - './project:/firebase'
